/* eslint-disable no-mixed-operators */
const list = [
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',
    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
  {
    campaignId: 'xzcxzc',

    time: new Date(`10-${Math.floor(Math.random() * 7 + 12)}-2023`),
    userId: '',
    value: Math.random() * 100,
  },
];
export default list;
